// lib/utils/builds/json_sterilizer.dart
library json_sterilizer;

import 'sterilizer_interface.dart';

class JsonSterilizer<T> implements SterilizerInterface<T> {
  @override
  Map<String, dynamic> toMap(T type) {
    throw UnimplementedError('Generated by build_runner');
  }

  @override
  T fromMap(Map<String, dynamic> jsonString) {
    throw UnimplementedError('Generated by build_runner');
  }

  @override
  T copyWith(T type) {
    throw UnimplementedError('Generated by build_runner');
  }

  @override
  String toString() {
    throw UnimplementedError('Generated by build_runner');
  }
}
